### ISSUE TITLE
What does your Project do?

### ISSUE THREAD

**Issue by Guelakais** [xRetry/esp32-config-tool#1]
I have been looking for ways to bring [ros2](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://docs.ros.org/en/humble/Tutorials.html&ved=2ahUKEwjSqtmggvuFAxVCg_0HHVAvCqwQFnoECBoQAQ&usg=AOvVaw3KrzlTkYAahWNGNyA_1u_4) with [rust](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.rust-lang.org/&ved=2ahUKEwiV1qutgvuFAxUygP0HHREPCNkQFnoECAcQAQ&usg=AOvVaw0Eo-jPMg1YR89Z4OceiP9Q) to a microcontroller for some time now. The main approach for ros2 on microcontrollers is usually [microros](https://micro.ros.org/). Your project looks like it does exactly that. Ros2 on a microcontroller. Unfortunately I can't really make heads or tails of the programme code. How exactly does it work and what does it do?

**Comment by solinvic** [comment]
This repo is just a CLI configuration tool, which sends parameters via ROS2 to the microcontroller.

For the project as a whole, I wrote a program for an ESP32 microcontroller and use MicroROS for communication. It basically maps GPIO pins to ROS2 messages. With the config tool in this repo, you can change this mapping at runtime.

The main repo for my project is [here](https://github.com/xRetry/ros2-esp32-interface).

(I should really start writing READMEs :sweat_smile:)
